### ISSUE TITLE
Would you support all tabs?

### ISSUE THREAD

**Issue by ivysrono** [hnakamur/FormatLink-Firefox#1]
The [Copy All Tab Urls WE](https://addons.mozilla.org/firefox/addon/copy-all-tab-urls-we/) does not support markdown and so on.

**Comment by hnakamur** [comment]
Sorry, that's out of my scope of this extension.
Maybe you can fork [Copy All Tab Urls WE](https://addons.mozilla.org/ja/firefox/addon/copy-all-tab-urls-we/) and implement the feature yourself.
