### ISSUE TITLE
Not working properly on FF 58.0b4

### ISSUE THREAD

**Issue by Explorare** [hnakamur/FormatLink-Firefox#18]
## Environment
FIrefox Dev Edition 58.0b4 (64-bit)
Format Link: 2.1.2

## Issue
No links nor texts shows up in the popup window on any website.

## Screenshot
![image](https://user-images.githubusercontent.com/5090766/32990462-af1a352c-cd64-11e7-881f-8313fbc4fd47.png)

**Comment by Explorare** [comment]
I tried to restore the default settings and it seems worked again, but kept showing the same link.
![image](https://user-images.githubusercontent.com/5090766/32990546-093cc302-cd66-11e7-955b-bed579a13312.png)

**Comment by Lin-Buo-Ren** [comment]
I have the exact same issue, remove and re-install the addon doesn't work.

**Comment by hnakamur** [comment]
Sorry for not responding. I'm closing this since it's too old.
