### ISSUE TITLE
Copy as default format by  hotkeys directly？

### ISSUE THREAD

**Issue by ivysrono** [hnakamur/FormatLink-Firefox#2]
For example, when press ctrl+f on anywhere, copy as default without click and confirm.

**Comment by hnakamur** [comment]
I added the keyboard shortcut Alt+C to copy the URL in the default format.
https://github.com/hnakamur/FormatLink-Firefox/commit/0c0214437bb1fcd9379972d20074c541866abed4

Please wait the version 1.3.0, which I submitted just now to be approved.
