### ISSUE TITLE
Adding Latex \href bug

### ISSUE THREAD

**Issue by asmwarrior** [hnakamur/FormatLink-Firefox#23]
Hi, the Latex `\href` has such format

`\href{<my_url>}{<description>}`

See this in the wikipedia page: [2.1.3 \href](https://en.wikibooks.org/wiki/LaTeX/Hyperlinks#\href)

But When I create on like below:
`\href{{{url}}}{{{text}}}`

I get the wrong result
`href{url}}}{text}}}`

The expect result could be:
`\href{https://www.wikibooks.org}{Wikibooks home}`

**Comment by asmwarrior** [comment]
As a workaround, this format works OK
`\href{ {{url}} }{ {{text}} }`
But the result string has some extra spaces, I don't want to add those spaces in the output text string.

**Comment by hnakamur** [comment]
@asmwarrior Sorry for being late.
You need to escape metacharacters like `\` or `{` with `\`.
I tried with the following config
`\\href\{{{url}}\}\{{{text}}\}`
and got the expected result:
`\href{https://www.wikibooks.org/}{Wikibooks}`

**Comment by asmwarrior** [comment]
OK, thanks for the help.
BTW: can your add those on your document(I mean the https://github.com/hnakamur/FormatLink-Firefox/blob/master/README.md, this is the only document of this add-on I see)
Thanks.

**Comment by hnakamur** [comment]
Thanks for your suggestion.
I added the explanation about escaping and the LaTeX example.
https://github.com/hnakamur/FormatLink-Firefox/commit/2af18f037b2f9f1018e9ef1d7000878b2d4f0ca5#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by asmwarrior** [comment]
Hi, good work! Thanks, so this issue can be closed now!
