### ISSUE TITLE
Replacing to empty string causes a parse error.

### ISSUE THREAD

**Issue by l3msh0** [hnakamur/FormatLink-Firefox#26]
Extension version: 3.0.1
Firefox version: 66.0.5 (macOS 10.14)

String substitution throws a parse error when trying to substitute some pattern to empty string.

e.g.  `{{title.s("aaa","")}}`

**Comment by cecoates** [comment]
I ran into this with the Chrome version as well:

https://github.com/hnakamur/FormatLink-Chrome/issues/10
