### ISSUE TITLE
No context menu entries with Nightly?

### ISSUE THREAD

**Issue by Radagast** [hnakamur/FormatLink-Firefox#3]
Everything seems to work, however, I'm not seeing any context menu entries with Nightly?

**Comment by hnakamur** [comment]
Sorry for confusion.
Please wait for 1.2.0 to be released at
https://addons.mozilla.org/ja/firefox/addon/format-link3/

**Comment by hnakamur** [comment]
Now version 1.3.0 is released.
https://addons.mozilla.org/ja/firefox/addon/format-link3/
