### ISSUE TITLE
Doesn't copy to clipboard in Linux

### ISSUE THREAD

**Issue by cmcqueen** [hnakamur/FormatLink-Firefox#30]
I'm using this extension at work on Firefox with Windows 7, and at home on Firefox with Ubuntu 19.10. It works really well on Firefox for Windows, but doesn't on Firefox for Linux. In the past, I've found it sometimes works, but I suspect only as long as I've never copied anything else to clipboard since I logged in. But most of the time, this extension doesn't work.

**Comment by cmcqueen** [comment]
Maybe use the newer [clipboard API `writeText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText).

**Comment by cmcqueen** [comment]
It may be that in `config:about`, resetting `dom.event.clipboardevents.enabled` back to `false` fixes it.

**Comment by hnakamur** [comment]
@cmcqueen Sorry for being late, I uploaded new version which uses clipboard.writeText API.
Could you try it?
And Thanks for your report and setting in `about:config`.

**Comment by cmcqueen** [comment]
Is that the version that was auto-updated yesterday? I have tested it, and it seems to be working fine.

**Comment by cmcqueen** [comment]
It seems to work even if `dom.event.clipboardevents.enabled` in `about:config` is set to `false`.

**Comment by hnakamur** [comment]
Thanks for your testing.
Yes, since version 4.0.0, it uses clipboard.writeText API as you suggested.
So, is it OK to close this issue now?

**Comment by cmcqueen** [comment]
Thanks for doing this! This is a very useful extension.
