### ISSUE TITLE
HTML, preserve paragraphs when pasting to TinyMCE visual editor (ClassicPress/WprdPress/etc.)?

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#35]
seems like WordPress might be doing something stupid here but i'm not sure

if i use the html template below with the html option checked and copy multiple paragraphs, when i paste into the WordPress visual editor the line feeds/paragraphs are not retained (paragraphs are run together)

`<h2><a href="{{url}}">{{title}}</a></h2>\n{{text}}`

this does not occur when pasting in a text editor however

**Comment by hnakamur** [comment]
Ah, I use copy as HTML for links only.
```
<a href="{{url.s("\"","&quot;")}}">{{text.s("<","&lt;")}}</a>
```

I confirmed the issue at the editor at wordpress.com.

![image](https://user-images.githubusercontent.com/19299/87794374-7bb4bc00-c881-11ea-8b58-12cfda251c42.png)

However I don't know what to do.

The current code copys the text as text/plain and as text/html like below:
https://github.com/hnakamur/FormatLink-Firefox/blob/5.0.1/clipboard-helper.js#L11-L12

**Comment by atomGit** [comment]
yeah, i don't understand this either - if you ctrl+c/v (including ctrl+shift+v to remove markup) then line feeds/paragraphs are preserved, so i don't know why they're lost with Format Link - and the same is true with [Link Text and Location Copier](https://addons.mozilla.org/en-US/firefox/addon/link-text-and-location-copier/) which is what i was using

somehow it seems that ctrl+c is writing clipboard data (or pasting?) differently than Format Link

with the HTML option enabled for a template, i assume this changes the MIME type to text/html - is there perhaps another MIME type for 'rich text' and could this be the issue?

**Comment by hnakamur** [comment]
I'm not familiar to the WordPress editor, but maybe this helps?
https://wordpress.stackexchange.com/questions/15394/extra-tinymce-editor-strips-p-and-br-tags/15666#15666

**Comment by atomGit** [comment]
that looks like it might be promising - thanks

**Comment by atomGit** [comment]
the SE solution didn't work, nor others i tried, however this is not a Format Link issue so closing ... thanks anyway!

**Comment by atomGit** [comment]
i'd like to re-open this issue since i think it may be possible to solve it

so the problem is that multiple paragraphs are combined when pasting in the WordPress visual editor

i wonder if wrapping `<p>/</p>` tags around the text would solve this issue? the text in the clipboard contains a line feed between paragraphs, so a simple RegEx might work here...

search: `^(.+)`
replace: `<p>\1</p>`

this isn't perfect of course,  but it could work well in a majority of cases

on the other hand, this may not work at all  because shouldn't the 'p' tags already be present in the clipboard when the HTML option is enabled in Format Link settings?

whatever the case, it sure would be great if a fix for this problem can be found

**Comment by atomGit** [comment]
this works...

`<p>{{text.s("\\n","</p><p>")}}</p>`

the full bit as i use it for pasting in ClassicPress/WordPress/TinyMCE visual editor...

`<a href="{{url}}">{{title.s("“|”|“|„|″","\"").s("‘|’|′","'")}}</a><p>{{text.s("“|”|„|″","\"").s("‘|’|′","'").s("\\n","</p><p>")}}</p>`

**Comment by atomGit** [comment]
this works for pasting in TinyMCE/Wordpress...

`<p>{{text.s("\\n+","</p><p>")}}</p>
