### ISSUE TITLE
re-institute HTML copy without selection

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#42]
i noticed in one of the change logs that the ability to copy in HTML format when nothing is selected is no longer possible

please reconsider this decision

quite often i need to be able to copy the page title/URL without having any text selected

**Comment by hnakamur** [comment]
You can copy the page title and the page URL when nothing is selected.
Without [Merge pull request #41 from hnakamur/use_link_only_when_text_is_selected · hnakamur/FormatLink-Firefox@e7eb318](https://github.com/hnakamur/FormatLink-Firefox/commit/e7eb31866ba2d4718ac1dfc5009438422a2ca4cf), the nearby link in the page was copied after clicking somewhere in the page.

**Comment by atomGit** [comment]
ok, then what i'm seeing is a bug apparently - i got in the habit of always selecting something because several times i tried to copy the page title & URL without a selection and the copy failed (the clipboard still contained the previously copied data)

**Comment by hnakamur** [comment]
Yeah maybe.
[new content not always copied · Issue #38 · hnakamur/FormatLink-Firefox](https://github.com/hnakamur/FormatLink-Firefox/issues/38) happens to me as well.
