### ISSUE TITLE
trouble with RegEx

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#45]
curious why this results in a parse error...

`{{text.s("\n").s("&nbsp;")}}`

**Comment by hnakamur** [comment]
Sorry for late reply.

* `s` takes two arguments.
* backslashes must be escaped twice, once for strings, once for regular expressions.

So here is the correct answer to replace newline (`\n`) characters to `&nbsp;`.

`{{text.s("\\\n","&nbsp;")}}`

**Comment by atomGit** [comment]
> Sorry for late reply.

i'm sorry also - i solved my problem but forgot about updating this issue
