### ISSUE TITLE
ignore 'text' variable when no text is selected

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#48]
i thought the default behavior was to ignore the `text` variable when no text is selected, however this is not working

page title: something
pattern: `{{title}}{{text}}`

produces 'somethingsomething'

**Comment by hnakamur** [comment]
Sorry, the document was wrong.
I just fixed it at https://github.com/hnakamur/FormatLink-Firefox/commit/c5cba5d932db43dbf719858fcbbfd78437afd641.

**Comment by atomGit** [comment]
thank you, but i was hoping for a different approach - i think it it would be better, and more intuitive for users, if the text variable were simply ignored if there was no text highlighted

**Comment by hnakamur** [comment]
I need `text` variable as is.
How about adding `selected_text` variable?

**Comment by atomGit** [comment]
sure - that would work

i don't understand though; the `selected_text` var would work exactly the same as `text`, no? so i'm wondering why you'd need a new variable

**Comment by hnakamur** [comment]
`text` variable value is not the same as `selected_text` since page title value is used if no text is selected.

`text` variable value is:

* the selected text if some text is selected,
* the link text if you open the context menu over a link,
* the page title otherwise.

**Comment by atomGit** [comment]
ah, i see

by the way, THANKS for continuing to work on this - it's a very useful extension!

**Comment by hnakamur** [comment]
Thanks for kind words.
I will merge [Add selected_text variable (fixes #48) by hnakamur · Pull Request #53 · hnakamur/FormatLink-Firefox](https://github.com/hnakamur/FormatLink-Firefox/pull/53) now.

**Comment by hnakamur** [comment]
I submitted version 5.3.0 to https://addons.mozilla.org/ja/firefox/addon/format-link3/
