### ISSUE TITLE
feature: global option for character replacements

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#49]
in many of the formatting options i add...

`<variable>.s("“|”|„|″","\"").s("‘|’|′","'")}}`

please consider adding a global option(s) to replace such characters with their plain equivalents 

[Yukisama/TextLinkyTool](https://github.com/Yukisama/TextLinkyTool) for example offers the following options...

Convert all type quotation to normal quotation.
Convert all type apostrophe to normal apostrophe.
Convert all type dash to normal dash.
Convert fullwidth space to normal space.
Delete context around space.(trim)
Delete invisible space.
Merge all type space to one space.

i think some of the above could be combined into 1 'format cleaning' option, perhaps all except the last one

**Comment by hnakamur** [comment]
How about adding global replacement options for each variable?

[Add global replace options by hnakamur · Pull Request #50 · hnakamur/FormatLink-Firefox](https://github.com/hnakamur/FormatLink-Firefox/pull/50/files)

![image](https://user-images.githubusercontent.com/19299/187936532-7ea6cfaa-d06f-4c2b-a71a-26080a8200a7.png)

**Comment by atomGit** [comment]
ah, yeah, perhaps that's even more useful - except i might suggest simplifying what you have in the screencap to just...

`"searchRegEx","replaceRegEx"` 

...or dividing the text input into 2 parts (search, replace) and eliminate the quotes altogether

**Comment by hnakamur** [comment]
Actually I implemented with two parts: searchRegEx and replacement string before this version.
However this version is better since it can deal with multiple replacements like:
`{{text.s("regexp1","replacement1").s("regexp2","replacement2")}}`

**Comment by atomGit** [comment]
i see - makes sense!
