### ISSUE TITLE
trouble replacing zero-width chars

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#56]
i want to remove zero-width characters, however this is not working

```
Title             Format 
test              {{text}}

Variable          Format
text              {{text.s("[^[:print:]*","")}}
```

this string contains zero-width chars: `this‌‌‌that`
when i copy it, this is the result: `titt`

**Comment by hnakamur** [comment]
`.s("[^[:print:]*","")` deletes any character except `[`, `:`, `p`, `r`, `i` , `n`, `t` since Regexp in JavaScript does not support POSIX character class like `:print:`

`{{text.s("[\\u200B]","")}}` can be used instead to remove zero-width characters.
